In [2]:
import numpy as np

In [3]:
A = np.ones((2,2))
B = np.ones((2,2))

## A is two dimensional vector (2,2) and B is two dimensional vector (2, 2)

---


In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

$$ A = \begin{bmatrix} 
1 & 2 \\
3 & 4 \\
\end{bmatrix}
\quad 
B = \begin{bmatrix} 
5 & 6 \\
7 & 8 \\
\end{bmatrix}
\quad
$$




np.matmul and np.dot
$ \begin{bmatrix} 
1 x 5 + 2 x 7 & 1 x 6 + 2 x 8 \\
3 x 5 + 4 x 7 & 3 x 6 + 4 x 8\\
\end{bmatrix}$ = $\begin{bmatrix} 
19 & 22 \\
43 & 50\\
\end{bmatrix}$

A * B = $ \begin{bmatrix} 
1 x 5 & 2 x 6 \\
3 x 7 & 4 x 8\\
\end{bmatrix}$ = $ \begin{bmatrix} 
5 & 12 \\
21 & 32\\
\end{bmatrix}$

In [6]:
C = np.matmul(A, B)
D = np.dot(A, B)
E = A * B

print('A: \n', A)
print('A.shape: \n', A.shape)
print('B: \n', B)
print('B.shape: \n', B.shape)
print('C: \n', C)
print('C.shape: \n', C.shape)
print('D: \n', D)
print('D.shape: \n', D.shape)
print('E: \n', E)
print('E.shape: \n', E.shape)

A: 
 [[1 2]
 [3 4]]
A.shape: 
 (2, 2)
B: 
 [[5 6]
 [7 8]]
B.shape: 
 (2, 2)
C: 
 [[19 22]
 [43 50]]
C.shape: 
 (2, 2)
D: 
 [[19 22]
 [43 50]]
D.shape: 
 (2, 2)
E: 
 [[ 5 12]
 [21 32]]
E.shape: 
 (2, 2)


## A is one dimensional vector (1,2) and B is two dimensional vector (2, 2)

---



$$ A = \begin{bmatrix} 
1 & 2 \\
\end{bmatrix}
\quad 
B = \begin{bmatrix} 
5 & 6 \\
7 & 8 \\
\end{bmatrix}
\quad
$$

np.matmul and np.dot
$ \begin{bmatrix} 
1 x 5 + 2 x 7 & 1 x 6 + 2 x 8 \\
\end{bmatrix}$ = $\begin{bmatrix} 
19 & 22 \\
\end{bmatrix}$

A * B = $ \begin{bmatrix} 
1 x 5 & 2 x 6 \\
1 x 7 & 2 x 8\\
\end{bmatrix}$ = $ \begin{bmatrix} 
5 & 12 \\
7 & 16\\
\end{bmatrix}$

In [4]:
A = np.array([1, 2])
B = np.array([[5, 6], [7, 8]])

In [5]:
print(A.shape)
print(B.shape)

(2,)
(2, 2)


In [6]:
C = np.matmul(A, B)
D = np.dot(A, B)
E = A * B

print('A: \n', A)
print('A.shape: \n', A.shape)
print('B: \n', B)
print('B.shape: \n', B.shape)
print('C: \n', C)
print('C.shape: \n', C.shape)
print('D: \n', D)
print('D.shape: \n', D.shape)
print('E: \n', E)
print('E.shape: \n', E.shape)

A: 
 [1 2]
A.shape: 
 (2,)
B: 
 [[5 6]
 [7 8]]
B.shape: 
 (2, 2)
C: 
 [19 22]
C.shape: 
 (2,)
D: 
 [19 22]
D.shape: 
 (2,)
E: 
 [[ 5 12]
 [ 7 16]]
E.shape: 
 (2, 2)


In [7]:
A = np.array([[1.],[2.]])
const_scalar =  2.
B  = np.array([[1.,2.,-1.],[3.,4.,-3.2]])

In [12]:
C = np.dot(A.T, B)  
#C = np.dot(B.T, A)        
D = np.matmul(A.T, B)
#D = np.matmul(A.T, B)

print('A: \n', A)
print('A.shape: \n', A.shape)
print('B: \n', B)
print('B.shape: \n', B.shape)
print('C: \n', C)
print('C.shape: \n', C.shape)
print('D: \n', D)
print('D.shape: \n', D.shape)
#print('E: \n', E)
#print('E.shape: \n', E.shape)

#A_DOT = sigmoid(np.dot(X.T, w) + b)                                   
#A_MAT = sigmoid(np.matmul(w.T, X) + b)                       

A: 
 [[1.]
 [2.]]
A.shape: 
 (2, 1)
B: 
 [[ 1.   2.  -1. ]
 [ 3.   4.  -3.2]]
B.shape: 
 (2, 3)
C: 
 [[ 7.  10.  -7.4]]
C.shape: 
 (1, 3)
D: 
 [[ 7.  10.  -7.4]]
D.shape: 
 (1, 3)


In [3]:
A = np.array([[1.],[2.]])
const_scalar =  2.
B  = np.array([[[1.,2.,-1.],[3.,4.,-3.2]], [[1.,2.,-1.],[3.,4.,-3.2]]])

In [4]:
print(B.shape)
print(B)

(2, 2, 3)
[[[ 1.   2.  -1. ]
  [ 3.   4.  -3.2]]

 [[ 1.   2.  -1. ]
  [ 3.   4.  -3.2]]]


In [5]:
C = np.dot(A.T, B)  
#C = np.dot(B.T, A)        
D = np.matmul(A.T, B)
#D = np.matmul(A.T, B)

print('A: \n', A)
print('A.shape: \n', A.shape)
print('B: \n', B)
print('B.shape: \n', B.shape)
print('C: \n', C)
print('C.shape: \n', C.shape)
print('D: \n', D)
print('D.shape: \n', D.shape)
#print('E: \n', E)
#print('E.shape: \n', E.shape)

#A_DOT = sigmoid(np.dot(X.T, w) + b)                                   
#A_MAT = sigmoid(np.matmul(w.T, X) + b)     

A: 
 [[1.]
 [2.]]
A.shape: 
 (2, 1)
B: 
 [[[ 1.   2.  -1. ]
  [ 3.   4.  -3.2]]

 [[ 1.   2.  -1. ]
  [ 3.   4.  -3.2]]]
B.shape: 
 (2, 2, 3)
C: 
 [[[ 7.  10.  -7.4]
  [ 7.  10.  -7.4]]]
C.shape: 
 (1, 2, 3)
D: 
 [[[ 7.  10.  -7.4]]

 [[ 7.  10.  -7.4]]]
D.shape: 
 (2, 1, 3)
